name: firebase_note
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  image_picker: ^0.8.4+11
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
